export const USER_GET_AUTH_REQUEST = "USER_GET_AUTH_REQUEST";
export const USER_GET_AUTH_SUCCESS = "USER_GET_AUTH_SUCCESS";
export const USER_GET_AUTH_FAIL = "USER_GET_AUTH_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";
