export enum authEnum {
  AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST",
  AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL",
  AUTH_LOGOUT_FAIL = "AUTH_LOGOUT_FAIL",
  AUTH_LOGOUT = "AUTH_LOGOUT",

  AUTH_REGISTER_REQUEST = "AUTH_REGISTER_REQUEST",
  AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS",
  AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL",
  AUTH_REGISTER_RESET = "AUTH_REGISTER_RESET",

  AUTH_CONFIRM_REQUEST = "AUTH_CONFIRM_REQUEST",
  AUTH_CONFIRM_SUCCESS = "AUTH_CONFIRM_SUCCESS",
  AUTH_CONFIRM_FAIL = "AUTH_CONFIRM_FAIL",

  AUTH_RESEND_REQUEST = "AUTH_RESEND_REQUEST",
  AUTH_RESEND_SUCCESS = "AUTH_RESEND_SUCCESS",
  AUTH_RESEND_FAIL = "AUTH_RESEND_FAIL",
  AUTH_RESEND_RESET = "AUTH_RESEND_RESEND",
}
