export enum authEnum {
  AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST",
  AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL",
  AUTH_LOGOUT_FAIL = "AUTH_LOGOUT_FAIL",
  AUTH_LOGOUT = "AUTH_LOGOUT",

  AUTH_REGISTER_REQUEST = "AUTH_REGISTER_REQUEST",
  AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS",
  AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL",
  AUTH_REGISTER_RESET = "AUTH_REGISTER_RESET",
}
