export enum fileEnum {
  FILE_URL_REQUEST = "FILE_URL_REQUEST",
  FILE_URL_SUCCESS = "FILE_URL_SUCCESS",
  FILE_URL_FAIL = "FILE_URL_FAIL",

  FILE_POST_REQUEST = "FILE_POST_REQUEST",
  FILE_POST_SUCCESS = "FILE_POST_SUCCESS",
  FILE_POST_FAIL = "FILE_POST_FAIL",

  FILE_AVATAR_UPDATE_REQUEST = "FILE_AVATAR_UPDATE_REQUEST",
  FILE_AVATAR_UPDATE_SUCCESS = "FILE_AVATAR_UPDATE_SUCCESS",
  FILE_AVATAR_UPDATE_FAIL = "FILE_AVATAR_UPDATE_FAIL",
  FILE_AVATAR_UPDATE_RESET = "FILE_AVATAR_UPDATE_RESET",
}
