export enum mailEnum {
  MAIL_CONFIRM_REQUEST = "MAIL_CONFIRM_REQUEST",
  MAIL_CONFIRM_SUCCESS = "MAIL_CONFIRM_SUCCESS",
  MAIL_CONFIRM_FAIL = "MAIL_CONFIRM_FAIL",

  MAIL_RESEND_REQUEST = "MAIL_RESEND_REQUEST",
  MAIL_RESEND_SUCCESS = "MAIL_RESEND_SUCCESS",
  MAIL_RESEND_FAIL = "MAIL_RESEND_FAIL",
  MAIL_RESEND_RESET = "MAIL_RESEND_RESEND",
}
