export enum postEnum {
  POST_LIST_REQUEST = "POST_LIST_REQUEST",
  POST_LIST_SUCCESS = "POST_LIST_SUCCESS",
  POST_LIST_FAIL = "POST_LIST_FAIL",

  POST_CREATE_REQUEST = "POST_CREATE_REQUEST",
  POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS",
  POST_CREATE_FAIL = "POST_CREATE_FAIL",
  POST_CREATE_RESET = "POST_CREATE_RESET",

  POST_DELETE_REQUEST = "POST_DELETE_REQUEST",
  POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS",
  POST_DELETE_FAIL = "POST_DELETE_FAIL",
}
