export enum userEnum {
  USER_GET_AUTH_REQUEST = "USER_GET_AUTH_REQUEST",
  USER_GET_AUTH_SUCCESS = "USER_GET_AUTH_SUCCESS",
  USER_GET_AUTH_FAIL = "USER_GET_AUTH_FAIL",
  USER_GET_AUTH_RESET = "USER_GET_AUTH_RESET",

  USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS",
  USER_UPDATE_FAIL = "USER_UPDATE_FAIL",
  USER_UPDATE_RESET = "USER_UPDATE_RESET",

  USER_LIST_REQUEST = "USER_LIST_REQUEST",
  USER_LIST_SUCCESS = "USER_LIST_SUCCESS",
  USER_LIST_FAIL = "USER_LIST_FAIL",
  USER_LIST_RESET = "USER_LIST_RESET",

  USER_DELETE_REQUEST = "USER_DELETE_REQUEST",
  USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS",
  USER_DELETE_FAIL = "USER_DELETE_FAIL",
  USER_DELETE_RESET = "USER_DELETE_RESET",

  USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST",
  USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS",
  USER_DETAILS_FAIL = "USER_DETAILS_FAIL",
  USER_DETAILS_RESET = "USER_DETAILS_RESET",

  USER_ADMIN_UPDATE_REQUEST = "USER_ADMIN_UPDATE_REQUEST",
  USER_ADMIN_UPDATE_SUCCESS = "USER_ADMIN_UPDATE_SUCCESS",
  USER_ADMIN_UPDATE_FAIL = "USER_ADMIN_UPDATE_FAIL",
  USER_ADMIN_UPDATE_RESET = "USER_ADMIN_UPDATE_RESET",
}
