export enum ztmEnum {
  ZTM_LIST_DETAILS_REQUEST = "ZTM_LIST_DETAILS_REQUEST",
  ZTM_LIST_DETAILS_SUCCESS = "ZTM_LIST_DETAILS_SUCCESS",
  ZTM_LIST_DETAILS_FAIL = "ZTM_LIST_DETAILS_FAIL",

  ZTM_GET_LOCATION_REQUEST = "ZTM_GET_LOCATION_REQUEST",
  ZTM_GET_LOCATION_SUCCESS = "ZTM_GET_LOCATION_SUCCESS",
  ZTM_GET_LOCATION_FAIL = "ZTM_GET_LOCATION_FAIL",
  ZTM_GET_LOCATION_RESET = "ZTM_GET_LOCATION_RESET",
}
